development:
  adapter: mysql2
  database: yobitch
  host: localhost
  username: root
  password: root
  encoding: utf8
  reconnect: true

staging:
  adapter: mysql2
  database: yobitch
  host: localhost
  username: root
  password: root
  encoding: utf8root
  reconnect: true  

production:
  adapter: mysql2
  database: yobitch
  host: localhost
  username: root
  password: root
  encoding: utf8
  reconnect: true
