# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 144592bd32825ce437868b4890c48de1eaa65fe63c3482da34266e526e12da507d7583a66e3f9fc91bb1ca9235c45687d912a0a55b97ceeae65d12723147ed33

test:
  secret_key_base: e769c6ff2e1038967ba665eccbb5fdcce84a265445a0468ffcd5774b63f1df911551c1aa2a5c7aa656b46d14d619d773ea28518ba5570c4f052dc6a3eca40703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Settings["SECRET_KEY_BASE"] %>
